services:
  # A Docker web service
  - type: web
    name: IMDb-Movie-Bot
    env: python
    startCommand: python3 main.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/KingstarStudios/IMDb-Movie-Bot # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: master # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMINS
        sync: false
      - key: DATABASE_URI
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: CHANNELS
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: IMDB
        sync: false
      - key: SINGLE_BUTTON
        sync: false
